In [37]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', 1010)
pd.set_option('display.max_rows', 1010)

In [40]:
df = pd.read_pickle('../data/pandas/features.pkl')

In [41]:
df['birthdate'] = pd.to_datetime(df['birthdate'], format='%d-%m-%Y', errors='coerce')

In [53]:
df[df['current.title'] == 'Cliënt rondt de betaling af'].head()

,_id,name,creation,current.activation_date,current.title,current.actor.email,current.actor.name,private_data.incorporation_type,first_name,last_name,email,phone_number,optional,identification_type,dutch,english,birthdate,date_of_issue,birthplace,marital_status,country_of_birth,postalcode,housenumber,housenumber_suffix,street,place_of_residence,country_of_residence,identification_number,bsn_number,country_of_issue,municipality_of_issue,salutation,type,shareholder_speaks_dutch,shareholder_speaks_english,shareholder_lives_in_holland,shareholder_signs_in_holland,bestuurder,aantal_aandelen,kapitaal,aandelen_begin,aandelen_eind,optionalContact,optionalAddress,shareholder_has_bsn,is_dutch_rechtspersoon,name_company,kvk_number,samen_of_alleen_oprichten,salutation_2,first_name_2,last_name_2,birthdate_2,birthplace_2,marital_status_2,country_of_birth_2,email_2,phone_number_2,postalcode_2,housenumber_2,street_2,place_of_residence_2,country_of_residence_2,identification_type_2,identification_number_2,bsn_number_2,country_of_issue_2,municipality_of_issue_2,date_of_issue_2,inbreng.name_company,inbreng.kvk_number,omzetting.name_company,omzetting.kvk_number,functie_bestuurder,housenumber_suffix_2,extra_holding_protection,wants_dga_package,disabledKvk,shareholder_has_bsn_2,bevoegdheid_bestuur,valuePerShare,rechtspersoon_is_bv
242,5e01c8ce758fa8eb7138abf1,CARPTOUR BENELUX,2019-12-24 08:14:06,2019-12-24 08:19:30,Cliënt rondt de betaling af,info@carptour.nl,None,BV,RJ,Tiber,randyjamestiber@gmail.com,0640103317,True,Paspoort,true,false,1968-08-09,02-02-2016,Heerlen,Ongehuwd en niet samenwonend,Nederland,6181BM,46,A,Koolweg,Elsloo,Nederland,NNF8H15D7,156788457,Nederland,SITTARD,Dhr.,1,ja,,ja,,true,120,€1.20,1,120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
698,5e0f79b9758fa87116f2ae5f,Good for Food,2020-01-03 17:28:25,2020-01-03 17:36:04,Cliënt rondt de betaling af,vankootensara1990@gmail.com,Sara van Kooten,BV,Sara,van Kooten,vankootensara1990@gmail.com,0636265999,True,Paspoort,true,false,1990-05-25,16-11-2015,Poznan,Ongehuwd en niet samenwonend,Polen,5623LB,270,NaN,Veldmaarschalk Montgomerylaan,Eindhoven,Nederland,NS6970PH1,212798029,Nederland,Eindhoven,Mevr.,1,ja,,ja,,true,120,€1.20,1,120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
311,5e665614551621d8308b4567,Brandon Lee Hoop Commercial Talent Representation,2020-03-09 14:43:32,2020-03-09 14:51:34,Cliënt rondt de betaling af,brandonlee@brandonleehoop.com,Brandon Lee Hoop,BV,Brandon Lee,Hoop,brandonlee@brandonleehoop.com,0657992126,True,Paspoort,true,false,1996-06-11,30-04-2019,Oss,Ongehuwd en niet samenwonend,Nederland,1012LZ,3,2,Nieuwendijk,Amsterdam,Nederland,NP288JDB1,223840749,Nederland,Amsterdam,Dhr.,2,ja,,ja,,true,120,€1.20,1,120,NaN,NaN,NaN,ja,Brandon Lee Hoop,NaN,alleen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nederland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
538,5e6b72b90e86676a4ba5b20a,defer,2020-03-13 11:47:05,2020-03-13 11:53:55,Cliënt rondt de betaling af,julianboldan@gmail.com,Julian Boldan,BV,Julian,Boldan,julianboldan@gmail.com,0675241423,True,Paspoort,false,true,2002-03-05,05-03-2020,Amsterdam,Gehuwd,België,1020 JG,300,NaN,heyt luivesytrats,amsterdam,Nederland,33213213,213213321,Nederland,amsterdam,Dhr.,1,nee,ja,ja,,true,120,€1.20,1,120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nederland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
636,5e70996c7f7e1d5846791cca,Dutch Star Trading Holding,2020-03-17 09:33:32,2020-03-17 09:43:06,Cliënt rondt de betaling af,tj@dscdubai.com,THEODORUS JANSEN,BV,Theodorus,Jansen,theodorusjansen3@gmail.com,00971506283010,True,Paspoort,true,false,1945-08-24,24-04-2019,Ede,Gehuwd,Nederland,125830,2905,"Willow Grove 2905, Green Community","Willow Grove 2905, Green Community",Dubai,Verenigde Arabische Emiraten,IHPFH2KD9,,Verenigde Arabische Emiraten,Dubai,Dhr.,1,ja,,nee,ja,true,120,€12000.00,1,120,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nederland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
df.groupby('shareholder_speaks_dutch').size().sort_values(ascending=False)

shareholder_speaks_dutch
ja     16150
nee      738
dtype: int64

In [50]:
df.groupby('private_data.incorporation_type').size().sort_values(ascending=False)

private_data.incorporation_type
BV           23207
Holding       7761
Stichting     1284
Spaar BV       271
dtype: int64

In [49]:
df.groupby('marital_status').size().sort_values(ascending=False)

marital_status
Ongehuwd en niet samenwonend    6686
Gehuwd                          6284
Ongehuwd en samenwonend         3151
Geregistreerd partnerschap       537
Ongehuwd en niet samanwonend     197
Ongehuwd en samanwonend           62
Geregristreed                     15
Geregistreed                       5
dtype: int64

In [52]:
df.groupby('place_of_residence').size().sort_values(ascending=False)

place_of_residence
Amsterdam         2572
Rotterdam         1058
's-Gravenhage      593
Utrecht            467
Almere             369
                  ...
Oostkapelle          1
Oostwold             1
Oploo                1
Opmeer               1
 's-Gravenhage       1
Length: 2060, dtype: int64

In [48]:
df.groupby('country_of_residence').size().sort_values(ascending=False)

country_of_residence
Nederland                       9122
Netherlands                      261
België                            91
Duitsland                         38
Spanje                            15
United Kingdom                    14
Verenigd Koninkrijk               13
Verenigde Staten                  11
Suriname                           9
Frankrijk                          8
Germany                            8
Spain                              7
India                              7
Greece                             6
China                              5
Zuid-Afrika                        5
United States                      5
France                             5
Namibië                            4
Vietnam                            4
Latvia                             4
Israël                             4
Rusland                            4
Italy                              4
Brazil                             4
Turkije                            4
Turkey                             4
Kazakhstan                         3
Verenigde Arabische Emiraten       3
Lebanon                            3
Czechia                            3
Thailand                           3
Canada                             3
Colombia                           3
Brazilië                           2
Hong Kong SAR China                2
Bulgarije                          2
Jamaica                            2
Australië                          2
Estonia                            2
Denemarken                         2
Monaco                             2
Japan                              2
Lithuania                          2
Tsjechische Republiek              2
Namibia                            2
Serbia                             2
Kaaimaneilanden                    2
Polen                              2
Cyprus                             1
Ukraine                            1
Belgium                            1
Sweden                             1
South Africa                       1
Singapore                          1
Saoedi-Arabië                      1
Roemenië                           1
Panama                             1
Portugal                           1
Palau                              1
Oostenrijk                         1
Oekraïne                           1
Noorwegen                          1
Haïti                              1
Mozambique                         1
Ierland                            1
Ireland                            1
Kroatië                            1
Australia                          1
dtype: int64

In [47]:
df.groupby('country_of_birth').size().sort_values(ascending=False)

country_of_birth
Nederland                       7634
Suriname                         220
Turkije                          161
Marokko                          154
Duitsland                         86
China                             81
Curaçao                           74
België                            65
India                             62
Iran                              60
Polen                             55
Syrië                             50
Afghanistan                       44
Verenigd Koninkrijk               41
Zuid-Afrika                       40
Netherlands                       40
Verenigde Staten                  31
Irak                              28
United Kingdom                    28
Egypte                            25
United States                     23
Vietnam                           23
Rusland                           23
Indonesië                         22
Bulgarije                         21
Pakistan                          19
Portugal                          18
Roemenië                          17
Frankrijk                         15
Somalië                           15
Bosnië en Herzegovina             15
Italië                            15
Spanje                            14
Aruba                             13
Italy                             12
Germany                           12
Brazilië                          12
South Africa                      11
Greece                            11
Oekraïne                          11
Australië                         11
Sri Lanka                         11
Brazil                            10
Thailand                          10
Colombia                           9
Zuid-Korea                         9
France                             9
Japan                              8
Israël                             8
Armenië                            8
Hongarije                          8
Griekenland                        8
Zwitserland                        8
Poland                             7
Kaapverdië                         7
Libanon                            7
Zweden                             7
Canada                             7
Turkey                             7
Ghana                              7
Ukraine                            7
Azerbeidzjan                       6
Kosovo                             6
Litouwen                           6
Tsjechische Republiek              6
Dominicaanse Republiek             6
Venezuela                          6
Australia                          6
Kroatië                            5
Nigeria                            5
Latvia                             5
Romania                            5
Spain                              5
Moldavië                           5
Togo                               4
Guatemala                          4
Hongkong SAR van China             4
Eritrea                            4
Ireland                            4
Lithuania                          4
Libië                              4
Bulgaria                           4
Oostenrijk                         4
Morocco                            4
Belgium                            4
Servië                             4
Burundi                            3
Congo-Kinshasa                     3
Filipijnen                         3
Sweden                             3
Georgië                            3
Slovakia                           3
Belarus                            3
Bangladesh                         3
Soedan                             3
Slowakije                          3
Zambia                             3
Peru                               3
Guyana                             3
Czechia                            3
Albanië                            3
Lebanon                            3
Jordanië                           3
Koeweit                            3
Russia                             3
Kenia                              3
Kazakhstan                         3
Saoedi-Arabië                      3
Sint-Maarten                       2
Ecuador                            2
Denemarken                         2
Singapore                          2
Tunisia                            2
Chili                              2
Estonia                            2
Caribisch Nederland                2
United Arab Emirates               2
Rwanda                             2
New Zealand                        2
Argentinië                         2
Angola                             2
Letland                            2
Guinee                             2
Finland                            2
Serbia                             2
Haiti                              2
Ethiopië                           1
Nieuw-Zeeland                      1
Botswana                           1
Saudi Arabia                       1
Bolivia                            1
Belize                             1
Nepal                              1
Haïti                              1
Slovenia                           1
Verenigde Arabische Emiraten       1
Uganda                             1
Noorwegen                          1
Oeganda                            1
Zimbabwe                           1
Anguilla                           1
IJsland                            1
Algerije                           1
Puerto Rico                        1
Namibië                            1
Brunei                             1
Taiwan                             1
Kazachstan                         1
Egypt                              1
Liberia                            1
Libya                              1
Dominica                           1
Syria                              1
Macedonia                          1
Maleisië                           1
Cuba                               1
Malta                              1
Montenegro                         1
Tunesië                            1
Kameroen                           1
Saint-Martin                       1
Ivoorkust                          1
Saint Lucia                        1
Cameroon                           1
Mexico                             1
Moldova                            1
Croatia                            1
dtype: int64

In [12]:
df.groupby('current.title')['_id'].nunique().sort_values(ascending=False)

current.title
Client vult de gegevens in                                   20746
Client fills out data                                         1308
Cliënt vult BV gegevens in                                    1050
Notaris stelt conceptakte op                                   383
Keur finale conceptakte goed                                   305
BV bijna opgericht!                                            230
Procedure in behandeling                                       169
Cliënt rondt de betaling af                                    145
Cliënt rond de betaling af                                      97
Voltooi de digitale identificatie van de oprichter(s)           52
Bespreking conceptakte                                          39
Cliënt vult gegevens aan                                        37
Ondertekening volmacht                                          32
Notary drafts draft deed of incorporation                       23
Lever fiscale documenten aan                                    21
Cliënt vult BV gegevens aan                                     15
Notaris registreert KvK nummer                                  12
Notaris uploadt KvK uittreksel                                   9
Client finishes the payment                                      8
Pending procedure                                                8
Approve final draft                                              8
upload de volmacht en PDC                                        7
BV almost incorporated!                                          6
Legalisatie bij de notaris                                       5
Documenten gereed maken voor digitale ondertekening              4
Complete the digital identification of the shareholder(s)        3
Explanation of draft deed                                        3
Approve final draft deed                                         3
Review inbreng documenten                                        2
Stichting bijna opgericht!                                       2
Keur finale concept- en inbrengakte goed                         2
Vul SBI codes in                                                 1
Notaris uploadt KvK uitreksel                                    1
Notary registers the Chamber of Commerce number                  1
Client adds additional information                               1
Upload de conceptakte                                            1
Name: _id, dtype: int64